### ISSUE TITLE
/req/pre-defined/enclosure-type

### ISSUE THREAD

**Issue by cportele** [INSPIRE-MIF/gp-ogc-api-features#11]
> ... containing a media type valid that is valid according to RFC 6838.

Beside that there "valid" is there twice, shouldn't the requirement be that the media type is registered by IANA (https://www.iana.org/assignments/media-types/media-types.xhtml)?

**Comment by heidivanparys** [comment]
INSPIRE also has a registry: http://inspire.ec.europa.eu/media-types/application 

> This register contains the sub-types of the media type application used for spatial data sets in INSPIRE, in particular in INSPIRE download services. Whenever sub-types exist that are registered with IANA or are in the registration process these are used. For all other formats, no commonly used sub-type exists and INSPIRE has to - at least temporarily - define their own types. In accordance with the rules for media types in RFC 2046/RFC 4288, these start with x-. At this time, all entries in this register have the status 'valid'. Sub-types that are no longer recommended for use will be marked as 'deprecated', but will always be kept in this register as download services may still be using deprecated sub-types.

**Comment by cportele** [comment]
Yes, I thought it was a deliberate decision in the drafting to open this and no longer constrain it to the types in the INSPIRE register. Although that would leave the question what to do with formats that have no IANA registered media types (everything with an "x-").

Interestingly, application/geo+json is missing from the INSPIRE register and should be added.
