### ISSUE TITLE
/req/pre-defined/collection-naming

### ISSUE THREAD

**Issue by cportele** [INSPIRE-MIF/gp-ogc-api-features#12]
> ... the name of the collection SHALL be the language-neutral name of the feature type as specified in the IRs for ISDSS

Then the examples need to be updated as they use `buildings` not `Building` or `addresses` not `Address`.

**Comment by alexanderkotsev** [comment]
@cportele - well spotted. Thanks. One additional issue to consider here would be case sensitivity. Maybe we can recommend, or explicitly ask url paths to be provided as lowercase. Additional details on that are provided in https://www.w3.org/TR/WD-html40-970708/htmlweb.html

**Comment by heidivanparys** [comment]
> One additional issue to consider here would be case sensitivity. Maybe we can recommend, or explicitly ask url paths to be provided as lowercase.

Then we need to state very clear that the interpretation of [IRs for ISDSS](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02010R1089-20131230) is that the case is not specified by these IRs, but will depend on the exact technology used and best practices for that technology.

![image](https://user-images.githubusercontent.com/11427611/72606532-0d695e00-391f-11ea-909b-c3e88110186b.png)

![image](https://user-images.githubusercontent.com/11427611/72606549-14906c00-391f-11ea-94f1-09fadd813656.png)

**Comment by alexanderkotsev** [comment]
The issue of naming of collections is addressed in 9877944
