### ISSUE TITLE
One Web API per INSPIRE data set?

### ISSUE THREAD

**Issue by michellutz** [INSPIRE-MIF/gp-ogc-api-features#2]
The Web API provides download access to one INSPIRE data set. For example, two data sets (with their own metadata records), one on buildings and one on addresses will have two landing pages (http://my-org.eu/addresses/ and http://my-org.eu/buildings/) rather than one landing page for the Web API (http://my-org.eu/oapif/) and two feature collections, one for each data set (http://my-org.eu/oapif/collections/addresses and http://my-org.eu/oapif/collections/buildings).

Would such an approach be feasible from an implementation point of view?

**Comment by cportele** [comment]
This is consistent with OGC API Features Core ("by default, every API implementing this standard will provide access to a single dataset"), so every implementation will (should) be able to support this. Support for multiple datasets in a single API is mentioned in the standard as a potential extension.

**Comment by heidivanparys** [comment]
OGC API Features - Core is clear on this point. So as I see it, if an implementer wants to serve different datasets from one API, then WFS 2.0 should be used.

Perhaps a few more informative lines on this should be added to the specification, but we cannot change the requirements of the specification.

Other opinions?

**Comment by alexanderkotsev** [comment]
We strictly follow the requirements of OGC API Features Part 1 (Core)
