### ISSUE TITLE
Unclear if a link to a metadata record is required

### ISSUE THREAD

**Issue by thijsbrentjens** [INSPIRE-MIF/gp-ogc-api-features#23]
In other download service specifications there is always a reference to a metadata document describing the dataset. The mapping of the INSPIRE NS metadata still is not final, maybe it will be described there. Maybe it could be mapped to a link in `/collections`, to point to some kind of metadata record.

**Comment by aaime** [comment]
I was about to open the same ticket... being able to link to an external metadata document seems useful, it's just a matter of finding the right "rel" value.

**Comment by heidivanparys** [comment]
This was actually discussed in the mapping document that was circulated in the MIG-T and is indeed missing from the current version of the Good Practice.

From https://eur-lex.europa.eu/eli/reg/2009/976/2010-12-28, 2.2.4. Spatial Data Sets Metadata parameters:

> The INSPIRE metadata elements of the available Spatial Data Sets shall be provided. In addition, for each Spatial Data Set, the list of those Coordinate Reference Systems referred to in Regulation (EU) No 1089/2010 which are available shall also be provided.

From the mapping document:

> INSPIRE Metadata can be provided as a link in the “links” array of type “describedBy” in the response Feature Collection metadata response document retrieved through a request to /collections

> Support to additional Coordinate Reference Systems is added by the upcoming “CRS” extension

See also https://github.com/opengeospatial/ogcapi-features/issues/102
