### ISSUE TITLE
Section 7.3 Requirements class INSPIRE-multilinguality

### ISSUE THREAD

**Issue by jsaligoe** [INSPIRE-MIF/gp-ogc-api-features#25]
7.3.1. INSPIRE-specific requirements
In agreement with @cportele comments [here](https://github.com/opengeospatial/oapi_common/issues/75#issuecomment-559193943) – we agree that “this goes beyond OGC API Common” and discussion of HTTP error codes. We raise concern about supporting this requirement. Initial implementation support for OGC API-Features across commercial and open source clients represents significant development work and refinement. We agree with the guiding principle that “INSPIRE-specific requirements” should remain consistent with the OGC API Features Core specification and not require INSPIRE-specific extensions.

Regarding OPEN QUESTION: How to test for /collections/{collectionId}/items/{featureId}? It would give way too much overhead to test every single feature. One feature? One feature in every collection? - We agree that testing every single feature with the described Accept-language test could cause an overhead – I think testing one or two features in every collection is sufficient.

**Comment by alexanderkotsev** [comment]
@jsaligoe this requirements class is mandatory for all data sets that contain information in more than one natural language, i.e. it is not applicable if the data sets containing one language (which would cover more than 99 % of the European use cases). 
That is why, including multilinguality into a separate requirements class decreases the burden on data providers.
