### ISSUE TITLE
How to deal with inherited dependencies

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/gp-ogc-api-features#29]
Currently, the spec says:

> | Requirements class | http://inspire.ec.europa.eu/id/spec/oapif-download/1.0/req/pre-defined |
> | --- | --- |
> | Target type | Web API |
> | Dependency | [OAPIF Requirements class "Core"](http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_requirements_class_core) |
> | Dependency | [OAPIF Requirements class "Open API 3.0"](http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_requirements_class_openapi_3_0)

INSPIRE-pre-defined-data-set-download-OAPIF is dependent on OpenAPI 3.0, which in turn is dependent on Core.

![image](https://user-images.githubusercontent.com/11427611/73653333-42004800-4689-11ea-9a46-60457a99a24a.png)

That means, that the dependency from INSPIRE-pre-defined-data-set-download-OAPIF to Core actually is redundant, as it has Core as a dependency already through OpenAPI 3.0, as also illustrated in the figure below (the redundant dependency in red).

![image](https://user-images.githubusercontent.com/11427611/73653528-a3281b80-4689-11ea-8a59-9d9f0271d3f2.png)

So how should we deal with this inherited dependency?

1. Remove the inherited dependency from the table.
2. Leave the dependency in the table, but use "Inherited dependency" in the left column. Note that in order to be consistent, the tables for requirements classes “INSPIRE-multilinguality” and  “INSPIRE-OAPIF-GeoJSON” would have to be updated too, and their inherited dependencies added.
3. Leave the table as it, and update the tables for requirements classes “INSPIRE-multilinguality” and  “INSPIRE-OAPIF-GeoJSON” so they include all inherited dependencies too.
4. ?

Additional question: would illustrating the dependencies by means of a diagram as the one above be useful?

**Comment by heidivanparys** [comment]
@cportele What would OGC recommend here? In the pull request I chose option 1.

**Comment by cportele** [comment]
@heidivanparys - Yes, this is the typical approach. Everything else leads to redundancies - and, as a result, potential inconsistencies.

**Comment by heidivanparys** [comment]
Ok, thanks.

@alexanderkotsev Could you merge the pull request?
