### ISSUE TITLE
How to test /req/multilinguality/accept-language-header for individual features?

### ISSUE THREAD

**Issue by michellutz** [INSPIRE-MIF/gp-ogc-api-features#3]
How to test the requirement /req/multilinguality/accept-language-header for /collections/{collectionId}/items/{featureId}? It would give way too much overhead to test every single feature. One feature? One feature in every collection?

**Comment by thijsbrentjens** [comment]
An OAPIF implementation shall support the limit parameter, so maybe use this to test a few features instead of a single feature using the {featureId}?

**Comment by alexanderkotsev** [comment]
We would like to propose an approach that tests five features per collection.
