### ISSUE TITLE
Requirement /req/multilinguality/accept-language-header

### ISSUE THREAD

**Issue by cportele** [INSPIRE-MIF/gp-ogc-api-features#36]
I would like to raise a concern about the requirement that servers must "return HTTP status code 406 when an Accept-Language HTTP header set to `*;q=0.0` is sent."

* ldproxy uses the Jersey library and its standard content negotiation mechanism, but ldproxy returns a 200. Debugging through the code shows that independent of what RFC 7231 says, "0.0" is not treated as "not acceptable", but rather as "least acceptable". To implement the requirement it seems as if we would need to implement special INSPIRE code to support that requirement and override the standard content negotiation mechanism.
* This is probably true in general. I have tried it with a number of other OGC API Features implementations and none of them returns a 406 for `*;q=0.0`.
* In general, this does not seem to be the typical practice on the Web either. I tried some websites (including Google, etc) and APIs and I have yet to find one that returns 406.

**Comment by heidivanparys** [comment]
@cportele I updated the clause on multilinguality (as well as Annex D). Could you please have a look?

@alexanderkotsev Could you have a look as well?

**Comment by cportele** [comment]
Thanks @heidivanparys, the changes look good to me :+1:
