### ISSUE TITLE
Bulk download and paging

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/gp-ogc-api-features#45]
This issue addresses one of the topics discussed in #22 .

Part of the topic has been addressed in the specification, by moving the requirements regarding bulk download to their own requirements class, "INSPIRE-bulk-download". That requirements class is described as _optional_ in the section on conformance.

However, I think that we should discuss whether that requirements class should be _conditional_ instead, the condition being: if the features in one or more of the collections cannot be retrieved with one request, the Web API shall implement requirements class "INSPIRE-bulk-download" (with other words: if paging is needed to retrieve all the features, the Web API shall implement requirements class "INSPIRE-bulk-download").

The topic should be looked at from different perspectives:

- From a legal point of view: how should the implementing rules be interpreted: does the legal text require a download "with one click" or would paging be ok as well?
- From a user-centric point of view: how useful is paging for a user that wants the whole dataset?
- From an implementation-centric point of view: how to make it clear that no paging is needed for a certain collection?

Arguments for the discussion are provided in #22 .

**Comment by alexanderkotsev** [comment]
In the spec for cases where data sets are too big for retrieval with a single API request, using multiple requests following the next links (paging) is considered to meet the requirements for a download service.
