### ISSUE TITLE
Bulk download and link relation type

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/gp-ogc-api-features#46]
This issue addresses one of the topics discussed in #22 .

This is actually the original question: https://github.com/INSPIRE-MIF/gp-ogc-api-features/issues/22#issue-547382244 The topic changed along the thread but is discussed again from here on: https://github.com/INSPIRE-MIF/gp-ogc-api-features/issues/22#issuecomment-573791098

So the questions are:

1. What link relation type to use for the link to a bulk download? `enclosure` or something else?
2. Should there be a recommendation regarding the `title` target attribute of the link to a bulk download?
3. Should there be a recommendation regarding a `length` target attribute of the link to a bulk download?
4. Should there be a requirement/recommendation regarding a target attribute that advertises the CRS of a bulk download?

Arguments for the discussion are provided in #22 .

**Comment by alexanderkotsev** [comment]
addressed in #63. Decision is to keep `enclosure`
