### ISSUE TITLE
Be more specific in /req/pre-defined/collection-naming

### ISSUE THREAD

**Issue by tervo** [INSPIRE-MIF/gp-ogc-api-features#51]
Current wording in req /req/pre-defined/collection-naming:
> For each collection that provides data that is harmonised according to the IRs for ISDSS, the id of the collection SHALL be the the lowercase version of the language-neutral name of the feature type as specified in the IRs for ISDSS.

is unclear. What is feature type in this context? Some explanation would be beneficial and it would be better to refer to a specific article / page number. 

How this should be interpreted in [Annex III](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A02010R1089-20131230&qid=1400675738563)? Data related to the themes Atmospheric Conditions or Meteorological Geographical Features shall be made available using the types defined in Specialised Observations package in Annex I, the OM_Observation spatial object type or sub-types thereof. Should all collections in that theme use the same name?

**Comment by heidivanparys** [comment]
Feature type is defined in the glossary, I am not sure how much more information we need?

Perhaps the additional documentation should describe this (for the second target group, see https://github.com/INSPIRE-MIF/gp-ogc-api-features/issues/20#issuecomment-685374028 )?

A link to a specific article would be good indeed. From https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02010R1089-20141231&from=EN#tocId7

> _Article 5_
> 
> **Types**
> 1.  For all types defined in this Regulation, a language-neutral name for computers is given between parentheses in the title of the section specifying the requirements for that type. This language-neutral name shall be used for referring to the corresponding type in the definition of an attribute or association role.

Examples:

https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02010R1089-20141231&from=EN#tocId187

> 5.2.1.    Address (Address) 

So the lowercase version would be `address`.

https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02010R1089-20141231&from=EN#tocId460

> 9.1.1    Protected Site (ProtectedSite) 

Here the lowercase version would be `protectedsite`.

**Comment by tervo** [comment]
Link / referance to specific article will help already a lot! And examples even more...

But then there's still a question about Annex III? For example theme AC-MF says:

> Data related to the themes Atmospheric Conditions or Meteorological Geographical Features shall be made available using the types defined in Specialised Observations package in Annex I, the OM_Observation spatial object type or sub-types thereof. 

In practice there are very different kind of data under same feature types. Should all collections in that theme use the same name?

**Comment by heidivanparys** [comment]
> What is feature type in this context?

Perhaps we could also refer to https://www.w3.org/TR/sdw-bp/#spatial-things-features-and-geometry

**Comment by tervo** [comment]
I think it's best to refer to explisit requirements in INSPIRE context. If we want to give some more information, those examples are the best way to make text more clear.

**Comment by alexanderkotsev** [comment]
Resolved in #63
