### ISSUE TITLE
Metadata link also as html

### ISSUE THREAD

**Issue by tervo** [INSPIRE-MIF/gp-ogc-api-features#52]
Current requirement `/req/pre-defined/spatial-data-set-metadata` requires metadata link as XML. It would be beneficial to have this link as html as well. The requirement could be augmented for example following:

_When HTML encoding is provided, corresponding link with `application/xml` `type` shall be provided._

**Comment by cportele** [comment]
+1 on the intention, but since the metadata is typically managed and shared by another server and we cannot be sure that all of them provide a URI for a html representation, I think linking to the metadata in HTML should be a recommendation, not a requirement.

**Comment by alexanderkotsev** [comment]
Definitely +1 to that one. Do we also need to also address JSON anticipating the conformance classes of 'OGC API - Records'?

**Comment by heidivanparys** [comment]
+1 to having a recommendation on providing a link to an HTML representation of the metadata. Should it be a general recommendation, or a recommendation that only is applicable when the Web API implements the [HTML requirements class](http://www.opengis.net/spec/ogcapi-features-1/1.0/req/html)?

**Comment by alexanderkotsev** [comment]
Resolved in #63
