### ISSUE TITLE
References to information about INSPIRE metadata needed

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/gp-ogc-api-features#54]
> #### Metadata elements of the data set
>
> | **Requirement** | **/req/pre-defined/spatial-data-set-metadata** |
> | --- | --- |
> | A | The response of the `/collections` operation SHALL include a link to the metadata record for the data set. This link SHALL have `rel` link parameter `describedby` and `type` link parameter `application/xml`. |
> 
> **TEST**
> 1. Issue an HTTP GET request to {root}/collections.
> 2. Validate that at least one of the links returned in the response has `rel` link parameter `describedby` and `type` link parameter `application/xml`.
> 3. For each of the links returned in the response having a `rel` link parameter `describedby` and `type` link parameter `application/xml`, issue an HTTP HEAD request to the path given in the `href` link parameter of that link.
> 4. Validate that for one of the responses the returned XML document satisfies one of the following:
>     - The document has root element `{http://www.opengis.net/cat/csw/2.0.2}GetRecordByIdResponse` followed by element `{http://www.isotc211.org/2005/gmd}MD_Metadata`.
>     - The document has root element `{http://www.isotc211.org/2005/gmd}MD_Metadata`.
>     - The document has root element `{http://standards.iso.org/iso/19115/-2/gmi/1.0}MI_Metadata`.

When discussing the specification with a developer of an implementation of OGC API - Features, that didn't really know INSPIRE, it became clear that the requirement and test in section "Metadata elements of the data set" needs an explanatory text with references to the IR metadata and TG metadata, and probably as well to the validator. Perhaps also a note about the fact that usually somebody else than the developer of the Web API will already have created this metadata, so it is a matter of finding out what the exact link is.

**Comment by PetrCoupek** [comment]
Current OAPIF 7.13 recommendation 9  is the relation expressed as  "describedBy" camel-Case variant (case-sensitive!).

**Comment by heidivanparys** [comment]
> Current OAPIF 7.13 recommendation 9 is the relation expressed as "describedBy" camel-Case variant (case-sensitive!).

That is a mistake that has been corrected in http://docs.opengeospatial.org/DRAFTS/17-069r4.html . See also opengeospatial/ogcapi-features#338

**Comment by heidivanparys** [comment]
This is addressed by the text following requirement /req/pre-defined/spatial-data-set-metadata
