### ISSUE TITLE
Recommendation to support cross-origin requests 

### ISSUE THREAD

**Issue by thijsbrentjens** [INSPIRE-MIF/gp-ogc-api-features#60]
For web applications support for cross-origin requests makes it easier to access an API directly (e.g using Javascript). The OGC spec recommends to support cross-origin request (https://docs.opengeospatial.org/is/17-069r3/17-069r3.html#cross_origin), see W3C too: https://www.w3.org/wiki/CORS_Enabled.

I propose to repeat this recommendation from the OGC Core specification in the INSPIRE Good practice or pay attention to it somehow.

**Comment by alexanderkotsev** [comment]
Note on CORS added in #63
