### ISSUE TITLE
Conformance Declaration

### ISSUE THREAD

**Issue by cportele** [INSPIRE-MIF/gp-ogc-api-features#62]
Is there an expectation that the implemented INSPIRE conformance classes are also published in the Conformance Declaration, i.e. under `/conformance`?

If the answer is yes, the Good Practice spec has to specify URIs for the conformance classes, too. Currently only URIs for the requirements classes are provided.

**Comment by alexanderkotsev** [comment]
Very important point. Thanks for raising this, and a pity that we missed this point during the regular call today. For me the answer is yes, and it would make sense to declare URIs for conformance classes as is done for the req. 

Any other thoughts?

**Comment by alexanderkotsev** [comment]
The opinions of the 2020.1 group on the topic of conformance declaration of INSPIRE specific classes would be very much appreciated! Also, does the API list the INSPIRE ones in addition to the ones already defined by the OGC, considering that the former depend on the latter.

**Comment by cportele** [comment]
One reason for not including INSPIRE conformance class URIs could be that fact that this may require code changes to the server. At least this is the case in ldproxy where the conformance class URIs in the conformance declaration are dynamically derived from the API itself. This ensures that the declaration is consistent with the API capabilities.

If we want to support INSPIRE conformance class URIs in the conformance declaration, we would need to add INSPIRE-specific code that checks against the additional INSPIRE requirements for each of the INSPIRE conformance classes. Will enough clients process the INSPIRE conformance class URIs to justify adding them?

(For a simpler solution that is not INSPIRE-specific, we could alternatively add a capability that one can configure arbitrary additional URIs for inclusion in the conformance declaration, but that introduces risks as one can easily make the conformance declaration inconsistent with the API definition. So that approach is questionable from the software architecture perspective.)

**Comment by alexanderkotsev** [comment]
I checked the [pygeoapi](url), and the conformance classes are provided through a [list of strings](https://github.com/geopython/pygeoapi/blob/master/pygeoapi/api.py). Do not know about the other implementations.

**Comment by alexanderkotsev** [comment]
Decision of the working group is to not include an explicit conformance declaration on the INSPIRE classes for the time being before understanding how clients and libraries are using the conformance declaration in practical terms.
