### ISSUE TITLE
The term OAPIF isn't properly defined

### ISSUE THREAD

**Issue by LtGlahn** [INSPIRE-MIF/gp-ogc-api-features#8]
The introduction uses the abbreviation OAPIF, but it does not appear to be properly defined. 

After thourough re-reading, I would guess that  `OAPIF  = OGC API - Features standard`, but I may be wrong. 

If I've guessed rigth, rewriting the last paragraph of the introduction to 
```
In order to facilitate the use of off-the-shelf software implementing the OGC API - Features standard (OAPIF) to meet... 
```
should solve this issue.

**Comment by alexanderkotsev** [comment]
Thanks for the suggestion. The text is modified accordingly.

**Comment by cportele** [comment]
I don't want to create an issue for this, so I just point out here in a comment that OAPIF is not used by OGC. Currently, there is no official short name. See https://github.com/opengeospatial/oapi_common/issues/35.
